platform :ios, '10.0'

source 'git@github.com:tokend/ios-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_modular_headers!

def main_pods
  pod 'TokenDSDK', path: '../'
  pod 'TokenDSDK/AlamofireNetwork', :path => '../'

  pod 'TokenDSDK/AlamofireNetworkJSONAPI', path: '../'
  pod 'TokenDSDK/RxJSONAPI', path: '../'

  pod 'SnapKit'
end

target 'TokenDSDK_Example' do
  main_pods
end

target 'TokenDSDK_Tests' do
  inherit! :search_paths

  main_pods
end

target 'TokenDSDK_IntegrationTests' do
  inherit! :search_paths

  main_pods
end
